import test,{before,after} from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';import http from 'node:http';import {once} from 'node:events';import {WebSocket} from 'ws';
import {createTestDatabase} from '../test-support/database.js';import {createUser,createSession} from '../db.js';import {attachOpsRadio,isAllowedRadioOrigin} from '../radio-server.js';
let database,server,relay,url;const clients=[];
before(async()=>{database=await createTestDatabase();server=http.createServer();relay=attachOpsRadio(server);server.listen(0,'127.0.0.1');await once(server,'listening');url=`ws://127.0.0.1:${server.address().port}/ops-radio`;});
after(async()=>{clients.forEach(c=>c.socket.terminate());await new Promise(r=>relay.wss.close(r));await new Promise(r=>server.close(r));await database.close();});
async function connect(name){let cookie='';if(name){const u=await createUser({username:name,passwordHash:'unused-test-hash',role:'ops'});const token=crypto.randomUUID();await createSession({userId:u.id,tokenSha256:crypto.createHash('sha256').update(token).digest('hex'),expiresAt:new Date(Date.now()+3600000).toISOString(),ip:'127.0.0.1'});cookie='FWSESS='+token;}
 const socket=new WebSocket(url,{headers:{Cookie:cookie}}),messages=[];socket.on('message',raw=>{try{messages.push(JSON.parse(raw.toString()));}catch{}});const client={socket,messages,wait(type,predicate=()=>true){const take=()=>{const i=messages.findIndex(m=>m.type===type&&predicate(m));return i>=0?messages.splice(i,1)[0]:null;};const existing=take();if(existing)return Promise.resolve(existing);return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{socket.off('message',receive);reject(new Error('Missing message '+type));},1500);const receive=()=>{const found=take();if(found){clearTimeout(timer);socket.off('message',receive);resolve(found);}};socket.on('message',receive);});},send(value){socket.send(JSON.stringify(value));}};clients.push(client);await once(socket,'open');return client;
}
test('radio origin validation rejects foreign sites and keeps same-origin/client compatibility',()=>{assert.equal(isAllowedRadioOrigin({headers:{host:'firewatchcz.cz',origin:'https://evil.test'}}),false);assert.equal(isAllowedRadioOrigin({headers:{host:'firewatchcz.cz',origin:'https://firewatchcz.cz'}}),true);assert.equal(isAllowedRadioOrigin({headers:{host:'firewatchcz.cz'}}),true);});
test('unauthenticated websocket receives auth_error and policy close',async()=>{const c=await connect();const closed=once(c.socket,'close');assert.equal((await c.wait('auth_error')).type,'auth_error');assert.equal((await closed)[0],1008);});
test('PCM relay grants only one transmitter and releases it across room changes',async()=>{
 const a=await connect('audit.radio.a'),b=await connect('audit.radio.b');await a.wait('auth_ok');await b.wait('auth_ok');a.send({type:'ptt_request'});assert.equal((await a.wait('ptt_granted',m=>m.self)).self,true);b.send({type:'ptt_request'});await b.wait('ptt_denied');
 a.send({type:'join_room',room:'TEST'});await b.wait('ptt_released');b.send({type:'ptt_request'});assert.equal((await b.wait('ptt_granted',m=>m.self)).self,true);b.send({type:'ptt_release'});await b.wait('ptt_released');
});
